### ISSUE TITLE
guard against vmOS not being available

### ISSUE THREAD

**Issue by h00die** [rapid7/vm-automation#21]
![image](https://user-images.githubusercontent.com/752491/101213375-49490700-3648-11eb-8f6b-ba74e6085686.png)

You need a guard for when the OS doesn't exist

```
>>> server.enumerateVms()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/vm_automation/esxiVm.py", line 194, in enumerateVms
    self.vmList.append(esxiVm(self, i))
  File "/home/user/.local/lib/python3.8/site-packages/vm_automation/esxiVm.py", line 491, in __init__
    if '64-bit' in self.vmOS:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by h00die** [comment]
that `_Pentest WindowsXP` is an archive for historical purposes, stop juding.

**Comment by h00die** [comment]
#20
